import setuptools

setuptools.setup(
    include_package_data = True,
    name = "dsdau",
    version = "0.0.1.3",
    description = "DAU Data Structure Modules",
    author = "SangKyunJeon",
    author_email = "sangkyun.jeon@gmail.com",
    url = "https://github.com/jsk0910/DAU_DS",
    download_url = "https://github.com/jsk0910/DAU_DS/archive/refs/tags/v0.0.1.3.zip",
    install_requires = ['pytest'],
    py_modules = ['list_.bidirectNode', 
                'list_.circularDoublyLinkedList', 
                'list_.circularDoublyLinkedListDemo', 
                'list_.circularLinkedList',
                'list_.circularLinkedListDemo',
                'list_.linkedListBasic',
                'list_.linkedListBasicDemo',
                'list_.listNode',
                'stack_.linkedStack',
                'stack_.linkedStackDemo',
                'stack_.listStack',
                'stack_.listStackDemo',
                'stack_.postfix',
                'stack_.reverseString',
                'sort_.bubbleSort',
                'sort_.bubbleSortDemo',
                'sort_.bucketSort',
                'sort_.bucketSortDemo',
                'sort_.countingSort',
                'sort_.countingSortDemo',
                'sort_.heapSort',
                'sort_.heapSortDemo',
                'sort_.insertionSort',
                'sort_.insertionSortDemo',
                'sort_.mergeSort',
                'sort_.mergeSortDemo',
                'sort_.quickSort',
                'sort_.quickSortDemo',
                'sort_.radixSort',
                'sort_.radixSortDemo',
                'sort_.selectionSort',
                'sort_.selectionSortDemo',
                'sort_.shellSort',
                'sort_.shellSortDemo',
                'queue_.linkedQueue',
                'queue_.linkedQueueDemo',
                'queue_.listQueue',
                'queue_.listQueueDemo',
                'queue_.palindrome',
                'heap_.heap',
                'heap_.heapDemo',
                'hashTable_.chainedHashTable',
                'hashTable_.chainedHashTableDemo',
                'hashTable_.hashOpenAddressed',
                'hashTable_.hashOpenAddressedDemo',
                'hashTable_.listHashTable',
                'hashTable_.listHashTableDemo',
                'BST.AVLTree',
                'BST.AVLTreeDemo',
                'BST.binarySearchTree',
                'BST.binarySearchTreeDemo'
                ],
    package_dir = {"": "DS"},
    packages=setuptools.find_packages(where='DS'),
    long_description = "Dong-A Univ. Data Structure Lecture Modules",
    long_description_content_type = "text/markdown",
    classifiers= [
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
)